name: e_commerce_grocery_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add any other dependencies you need here
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  dropdown_button2: ^2.0.6
  flutter_quill: ^10.8.5
  url_launcher: ^6.3.1
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  carousel_slider: ^5.0.0
  provider: 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Specify your assets here if needed
  assets:
    - assets/
